### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Lalit64** [Axenide/PywalZen#3]
I don't understand how to get it to work, 
edit: so basically frame and the area around the url bar is not themed accordingly
<img width="1800" alt="Screenshot 2024-12-07 at 1 25 21 PM" src="https://github.com/user-attachments/assets/6d29343e-bdf6-4561-89d6-43658ab93452">

**Comment by Axenide** [comment]
I asked the devs to update the theme a while ago. It works, but the PR has't been merged yet.
You can add the CSS from this repo to your userChrome.css to make it work and set the flags in about:config for your darkness level.
