### ISSUE TITLE
 Problem with colors after using Pywal, PywalFox and PywalZen 

### ISSUE THREAD

**Issue by deljanin** [Axenide/PywalZen#4]
After using Pywal, PywalFox and PywalZen, my context menu text became dark gray, and some other visual anomalies appeared like when managing bookmarks in the manage bookmarks sub menu, some rows would have a white background and so the text couldn't be read as it was also white, and some rows appeared with dark background which was correct.

I removed pywalfox and pywalzen, then I tried reinstalling zen browser.

I also tried removing the .zen folder and then reinstalling .zen. None of that worked.

So I think the problem is that when I used pywalzen and pywalfox, they changed some color scheme setting somewhere in the config that is not related to profiles. I have that same issues regardless of profile. The only thing that worked was installing the unoptimized version of zen (zen-browser-bin 1.0.1.a.22-1), which makes sense as it's an entirely different program with different config locations.

Does anybody have any idea how to fix this?

Additional info: Archlinux with Hyprland, and yay.
zen-browser-avx2-bin 1.0.1.a.22-1 

![2024-12-10-035445_hyprshot](https://github.com/user-attachments/assets/0eab7a66-8422-4341-9168-cf6592251ed5)
![2024-12-10-035729_hyprshot](https://github.com/user-attachments/assets/117c0821-a9c9-4b72-bf82-1d05a117baf4)

**Comment by Axenide** [comment]
Hi! The PR for updating PywalZen hasn't been merged yet. That's why it isn't working in the latest version!
An alternative would be adding the CSS in this repo to you userChrome.css and adding your desired flags in `about:config` for darkness level.
I bumped the PR a few days ago, I hope the devs merge it soon.

**Comment by deljanin** [comment]
Ok, thank you for the quick response!
