### ISSUE TITLE
No color change in places like dropdown menus, settings etc. 

### ISSUE THREAD

**Issue by Sain-Biswas** [Axenide/PywalZen#5]
The pywal fox firefox theme is unable to set userchrome.css file and even pywalZen is not doing so

Does anyone know how to apply colors to all places or it's really a bug?

**Comment by Axenide** [comment]
Hi! Thank you for referring that link too, it was useful.
Everything is working fine for me. Do you get any connection errors in PywalFox? I had that problem a few days ago and the solution was deleting the .mozilla folder.
PywalZen is working, as long as PywalFox works too. I haven't found anything that isn't themed yet.
Are you using the latest Zen Browser version? (1.0.2-b.2)
Tho it worked with alpha versions too so I don't really know if that could be a problem either.

**Comment by Sain-Biswas** [comment]
yes I am using the latest version 1.0.2-b.2(zen-browser-avx2-bin) on arch linux

The new ui may be the reason but the settings page, and options dropdown in main browser window are not styled

rest parts of the ui are themed
![Screenshot 2024-12-20 114033](https://github.com/user-attachments/assets/340d7ee6-d69f-4e55-8057-160f25ff6c38)

By dropdown menu i mean this part

**Comment by Axenide** [comment]
Ah, sure! I'll see what I can do. Now that I checked it mine isn't themed either, it was literally an optical illusion caused by the surrounding colors lol.

**Comment by Axenide** [comment]
I solved it, now you have to wait for the Zen Browser devs to update the theme, or you can just put the CSS in your userChrome.css too!
Thanks!

**Comment by Axenide** [comment]
Hi @Sain-Biswas, just wanted to let you know that the mod has been updated in the Themes Store!

**Comment by Sain-Biswas** [comment]
Thanks for the update
